apiVersion: v1
kind: Secret
metadata:
  name: ldap-password
  namespace: kubeaddons
type: Opaque
stringData:
  password: Secret123
---
apiVersion: dex.mesosphere.io/v1alpha1
kind: Connector
metadata:
  name: ldap
  namespace: kubeaddons
spec:
  enabled: true
  type: ldap
  displayName: LDAP Test
  ldap:
    host: ipa.demo1.freeipa.org:389
    insecureNoSSL: true
    bindDN: uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org
    bindSecretRef:
      name: ldap-password
    userSearch:
      baseDN: cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org
      filter: "(objectClass=person)"
      username: uid
      idAttr: uid
      emailAttr: mail
    groupSearch:
      baseDN: cn=groups,cn=accounts,dc=demo1,dc=freeipa,dc=org
      filter: "(objectClass=groupofnames)"
      userAttr: DN
      groupAttr: uniqueMember
      nameAttr: cn
